name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [notes-update]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout www repository
        uses: actions/checkout@v3

      - name: Checkout notes repository
        uses: actions/checkout@v3
        with:
          repository: felixmurraytang/notes
          path: src/content/notes

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name felixmurraytang
