name: blog

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [notes-update]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout felixmurraytang/org
        uses: actions/checkout@v4
        with:
          repository: felixmurraytang/org
          path: src/content/org
          token: ${{ secrets.BLOG }}
      
      - name: Remove unused folder
        run: cd src/content/org && rm -fr journal resume
          
      - name: Setup
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name ${{ github.event.repository.name }}